<div id="container">
    <?php $form = $this->get('form'); ?>
    <?= $form->openTag(); ?>
    
<!--    <fieldset>
      <legend>Usergroup:</legend>-->
      <?= $form->renderAllToRows(); ?>
<!--    </fieldset>-->
    <?= $form->formElement('submit'); ?>
    <?= $form->closeTag(); ?>
</div>

<script src="/widgets/chosen/chosen.jquery.min.js"></script>

<script>
    $(document).ready(function() {
        $("#routeForm")
                .ajaxForm({
                    beforeSerialize: function() {
                        $("#loader").show();
                    },
                    success: function(response, status, xhr){
                        $("#loader").hide();
                        adminLoader(response,xhr);
                    }
                })
                .initWidgets(['chosen']);
    });
</script>