<noscript>
    <div style="position: fixed; display: block; width:100%; height: 100%; z-index: 100; text-align: center; font-size: 24px; color: #555555; background-color: #F7F7F7; padding: 24px;">
        To view this site you need a JavaScript compilant browser first.
    </div>
</noscript>
<div class="site-header color-light">
  <a href="http://<?php echo $_SERVER['SERVER_NAME']; ?>" class="site-header-element-container" title="Ivótérkép">
    <div class="header-text site-header-logo">
    </div>
    <div class="site-header-element header-text">
      Ivótérkép
    </div>
  </a>

  <div class="site-header-element-container margin-align-vertical-middle" style="flex-grow: 1">
    <input id="searchbox" git type="text" placeholder="Cím keresése.." class="box-element input-field input-field-text site-header-searchbox" />
  </div>

  <?= $this->get('site-header') ?>
</div>
<div class="site-content">
    <?= $this->get('site-content') ?>
</div>
<div class="site-footer color-light">
  Footertinks
  <?= $this->get('site-footer') ?>
</div>