<?php $form = $this->get('form'); ?>
<?= $form->openTag() ?>
    <div class="label-text">
        Felhasználónév
    </div>
    <?= $form->formElement('username') ?>
    <div class="label-text">
        Jelszó
    </div>
    <?= $form->formElement('password') ?>
    
    <?= $form->formElement('login') ?>
<?= $form->closeTag() ?>

<script>
    $("#loginForm").ajaxForm({
      //  url: '/____/login/login',
        type: 'post',
        success: function(){
            location.reload();
        }
    });
//    $('#loginForm').submit(function(e){ console.log('asd');
//        e.preventDefault();
//        $.ajax({
//            method: 'POST',
//            data:
//        });
//    });
</script>