<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkUOdZ5y7hMm0yrcCQoCvLwzdM6M8s5qk&callback=initMap" async defer></script>
<script>
    var map;

function initMap() {
  map = new google.maps.Map(document.getElementById('map'), {
    center: {
      lat: 47.532300,
      lng: 21.629500
    },
    zoom: 16,
    disableDoubleClickZoom: true,
    disableDefaultUI: true,
    gestureHandling: "greedy",
    clickableIcons: false,
    styles: [{
      featureType: 'poi.business',
      elementType: 'all',
      stylers: [{
        visibility: 'off'
      }]
    }, {
      featureType: 'poi.park',
      elementType: 'labels.icon',
      stylers: [{
        visibility: 'off'
      }]
    }]
  });

  map.addListener('dragend', mapEventHandler)
  map.addListener('zoom_changed', mapEventHandler)

  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var pos = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };
      //map.setCenter(pos);
      map.setZoom(17);
      //console.log('User origin is: ' + map.getCenter().toString());
    });
  }

}

function mapEventHandler() {
  //console.log('New origin is: ' + map.getCenter().toString());
  //console.log('New bounds are: ' + map.getBounds().toString());
}
</script>
<div id="map"></div>
<?= $this->get('valami'); ?>