<div class="popup-content">
    <?php $data = $this->get('data'); ?>
    
    <img class="thumb-img" src="/<?= $data['imagePath'] ?>">
    
    <div class="open-time">
        <h2>
            <?= $data['name']?>
        </h2>
        <h3>
            Nyitvatartás:
        </h3>
        Hétfő: <?= $data['open']['monday'] ?> - <?= $data['close']['monday'] ?><br>
        Kedd: <?= $data['open']['tuesday'] ?> - <?= $data['close']['tuesday'] ?><br>
        Szerda: <?= $data['open']['wednesday'] ?> - <?= $data['close']['wednesday'] ?><br>
        Csütörtök: <?= $data['open']['thursday'] ?> - <?= $data['close']['thursday'] ?><br>
        Péntek: <?= $data['open']['friday'] ?> - <?= $data['close']['friday'] ?><br>
        Szombat: <?= $data['open']['saturday'] ?> - <?= $data['close']['saturday'] ?><br>
        Vasárnap: <?= $data['open']['sunday'] ?> - <?= $data['close']['sunday'] ?><br>        
    </div>
    <div class="pub-attributes">
        <p id="address">
            <?= $data['address'] ?>
        </p>
        <p id="email">
            <?= $data['email'] ?>
        </p>
        <p id="phone">
            <?= $data['phone'] ?>
        </p>
        <p id="comment">
            <?= $data['comment']?>
        </p>
    </div>

</div>