<?php
    $isOpenTimeValid = function($data, $day)
    {
        if (isset($data['open'][$day]) && isset($data['close'][$day])) {
            return true;
        } else {
            return false;
        }
    };
?>

<!--<div class="popup-content">-->
    <?php $data = $this->get('data');?>
    
    <?php if($data['imagePath']): ?>
        <div class="thumb-img" style="background-image: url('/<?= $data['imagePath'] ?>')"><br><br><br><br></div><!-- nem látta senki !>
    <?php endif; ?>
<!--    <h2>
        <?= $data['name']?>
    </h2>-->
        Közvetlen link:&nbsp;<a href='https://<?php echo $_SERVER['SERVER_NAME']; ?>/<?= $data['sef'] ?>'>
            https://<?php echo $_SERVER['SERVER_NAME']; ?>/<?= $data['sef'] ?>
        </a>
        <?php if ($data['address']) { ?>
            <p id="address">
                Cím: <?= $data['address'] ?>
            </p>
        <?php } ?>
    <div class="isOpen">
        <?php if(isset($data['opened'])){
                switch ($data['opened']) {
                    case 'open':
                        echo '<div class="green">Jelenleg nyitva!</div>';
                        break;
                    case 'close':
                        echo '<div class="red">Jelenleg zárva</div>';
                        break;
                    case '1hour':
                        echo '<div class="yellow">Egy órán belül zár.</div>';
                        break;
                    default:
                        echo 'Nincs nyitvatartási adat a mai napra.';
                }} else {
                     echo 'Nincs nyitvatartási adat a mai napra.';
                }
            ?>
    </div>
    <div class="open-time">
        <h3>
            Nyitvatartás:
        </h3>
        <div>
            <div class="" style="display: inline-block; float: left; margin-right:10px;">
                <div>Hétfő:</div>
                <div>Kedd:</div>
                <div>Szerda:</div>
                <div>Csütörtök:</div>
                <div>Péntek:</div>
                <div>Szombat:</div>
                <div>Vasárnap:</div>
            </div>
            <div style="display: inline-block; float: left; text-align: center;">
                <?php if ($isOpenTimeValid($data, 'monday')) {?>
                <div><?= $data['open']['monday'] ?> - <?= $data['close']['monday'] ?></div>
                <?php } else { ?>
                <div>Nincs adat</div>
                <?php } ?>
                <?php if ($isOpenTimeValid($data, 'tuesday')) {?>
                <div><?= $data['open']['tuesday'] ?> - <?= $data['close']['tuesday'] ?></div>
                <?php } else { ?>
                <div>Nincs adat</div>
                <?php } ?>
                <?php if ($isOpenTimeValid($data, 'wednesday')) {?>
                <div><?= $data['open']['wednesday'] ?> - <?= $data['close']['wednesday'] ?></div>
                <?php } else { ?>
                <div>Nincs adat</div>
                <?php } ?>
                <?php if ($isOpenTimeValid($data, 'thursday')) {?>
                <div><?= $data['open']['thursday'] ?> - <?= $data['close']['thursday'] ?></div>
                <?php } else { ?>
                <div>Nincs adat</div>
                <?php } ?>
                <?php if ($isOpenTimeValid($data, 'friday')) {?>
                <div><?= $data['open']['friday'] ?> - <?= $data['close']['friday'] ?></div>
                <?php } else { ?>
                <div>Nincs adat</div>
                <?php } ?>
                <?php if ($isOpenTimeValid($data, 'saturday')) {?>
                <div><?= $data['open']['saturday'] ?> - <?= $data['close']['saturday'] ?></div>
                <?php } else { ?>
                <div>Nincs adat</div>
                <?php } ?>
                <?php if ($isOpenTimeValid($data, 'sunday')) {?>
                <div><?= $data['open']['sunday'] ?> - <?= $data['close']['sunday'] ?></div>
                <?php } else { ?>
                <div>Nincs adat</div>
                <?php } ?>
            </div>
        </div> 
    </div>
    <div class="pub-attributes">
        <?php if($data['cheapestBeer']): ?>
            <p>
                Legolcsóbb sör ára: <?= $data['cheapestBeer'] ?> Ft
            </p>
        <?php endif; ?>
        <?php if($data['email']): ?>
            <p id="email">
                E-mail cím: <?= $data['email'] ?>
            </p>
        <?php endif; ?>
        <?php if($data['phone']): ?>
            <p id="phone">
                Telefonszám: <?= $data['phone'] ?>
            </p>
        <?php endif; ?>
        <?php if($data['comment']): ?>
            <p id="comment">
                <?= $data['comment']?>
            </p>
        <?php endif; ?>
    </div>
      
    <input type="button" class="submit-button" style="display: inline; margin: 10px 5px 10px 5px;" onClick="calcRoute({lat: Number('<?= $data['latitude']?>'), lng:Number('<?= $data['longitude']?>')})" value="Útvonal ide!">
<!--</div>-->