<div class="popup-content">
    <?php $data = $this->get('data'); ?>
    
    <?php if($data['imagePath']): ?>
        <img class="thumb-img" src="/<?= $data['imagePath'] ?>">
    <?php endif; ?>
    <h2>
        <?= $data['name']?>
    </h2>
    <div class="isOpen">Jelenleg: 
        <?php if(isset($data['opened'])){
                switch ($data['opened']) {
                    case 'open':
                        echo 'Nyitva!';
                        break;
                    case 'close':
                        echo 'Zárva';
                        break;
                    case '1hour':
                        echo 'Egy órán belül zár';
                        break;
                    default:
                        echo 'Nincs adat :(';
                }} else {
                     echo 'Nincs adat :(';
                }
            ?>
    </div>
    <div class="open-time">
        <h3>
            Nyitvatartás:
        </h3>
        Hétfő: <?= $data['open']['monday'] ?> - <?= $data['close']['monday'] ?><br>
        Kedd: <?= $data['open']['tuesday'] ?> - <?= $data['close']['tuesday'] ?><br>
        Szerda: <?= $data['open']['wednesday'] ?> - <?= $data['close']['wednesday'] ?><br>
        Csütörtök: <?= $data['open']['thursday'] ?> - <?= $data['close']['thursday'] ?><br>
        Péntek: <?= $data['open']['friday'] ?> - <?= $data['close']['friday'] ?><br>
        Szombat: <?= $data['open']['saturday'] ?> - <?= $data['close']['saturday'] ?><br>
        Vasárnap: <?= $data['open']['sunday'] ?> - <?= $data['close']['sunday'] ?><br>        
    </div>
    <div class="pub-attributes">
        <p id="address">
            Cím: <?= $data['address'] ?>
        </p>
        <?php if($data['email']): ?>
            <p id="email">
                E-mail cím: <?= $data['email'] ?>
            </p>
        <?php endif; ?>
        <?php if($data['phone']): ?>
            <p id="phone">
                Telefonszám: <?= $data['phone'] ?>
            </p>
        <?php endif; ?>
        <?php if($data['comment']): ?>
            <p id="comment">
                <?= $data['comment']?>
            </p>
        <?php endif; ?>
    </div>
      
    <input type="button" class="submit-button" style="display: inline; margin: 10px 5px 10px 5px;" onClick="createRoute()" value="Útvonal ide!">

    <script>
        function createRoute(){
            calcRoute({lat: Number('<?= $data['latitude']?>'), lng:Number('<?= $data['longitude']?>')});
        }
    </script>
</div>