<div id="container">
    <?php $form = $this->get('form'); ?>
    
    <?= $form->openTag(); ?>
    <fieldset>
        <legend>Általános beáll.:</legend>
        <div class="c12 colpadding">
            <?= $form->formElement('name'); ?>
        </div>
        <div class="c2 colpadding clear">
            <div class="leadIm">
                <?= $form->formElement('image'); ?>
            </div>
            <?= $form->formElement('no_image'); ?>
        </div>
        <div id="img_preview" class="c10">
            <img id="previewimg" src="">
        </div>
        <div class="c12 colpadding">
            <?= $form->formElement('address'); ?>
        </div>
        <div class="c12 colpadding">
            <?= $form->formElement('comment'); ?>
        </div>
        <div class="c12 colpadding">
            <?= $form->formElement('sef'); ?>
        </div>
    </fieldset>
    <fieldset>
        <legend>Elérhetőségek:</legend>
        <div class="c6 colpadding">
            <?= $form->formElement('email'); ?>
        </div>
        <div class="c6 colpadding">
            <?= $form->formElement('phone'); ?>
        </div>
    </fieldset>
    <fieldset>
        <legend>Koordináták:</legend>
        <div class="c6 colpadding">
            <?= $form->formElement('latitude'); ?>
        </div>
        <div class="c6 colpadding">
            <?= $form->formElement('longitude'); ?>
        </div>
    </fieldset>
    <fieldset>
        <legend>Nyitvatartás:</legend>
        <table>
        <?php $days = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
        foreach ($days as $key) { ?>
            <tr>
                <td>
                    <?= $key ?>
                </td>
                <td>
                    <?= $form->formElement('open',null,null,$key); ?>
                </td>
                <td> - </td>
                <td>
                    <?= $form->formElement('close',null,null,$key); ?>
                </td>
            </tr>
        <?php } ?>
        </table>
    </fieldset>

    <?= $form->formElement('submit'); ?>
    <?= $form->closeTag(); ?>
</div>

<script src="/widgets/tinymce/tinymce.min.js"></script>
<script src="/widgets/tinymce/jquery.tinymce.min.js"></script>
<script src="/widgets/chosen/chosen.jquery.min.js"></script>
<script>

    $(document).ready(function () {
        $("#pubForm")
                .ajaxForm({
                    beforeSerialize: function () {
                        //  $("#loader").show();
                    },
                    success: function (response, status, xhr) {
                        //   $("#loader").hide();
                        adminLoader(response, xhr);
                    }
                })
                .hideElements([
                    {element: '#no_lead_image', values: [true], hideElements: '.leadIm,#img_preview'}
                ]);

        $(".tinymce").tinymce({
            elementpath: false,
            height: 400,
            max_height: 1000,
            statusbar: false,
            paste_data_images: true,
            file_picker_types: 'image',
            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            images_upload_url: '/hejj/ho',
            automatic_uploads: true,
            file_picker_callback: function (callback, value, meta) {
                callback('https://storage.googleapis.com/gweb-uniblog-publish-prod/static/blog/images/google-200x200.7714256da16f.png', {});

                if (meta.filetype == 'image') {
                    $('#tmce_upl').trigger('click');
                }
            }
        });

        $("#image").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewimg').attr('src', e.target.result);
                };
                reader.readAsDataURL(this.files[0]);
            }
        });
    });
</script>